export const Customers = [
  [{ 'id':1, 'first_name':'Olive', 'last_name':'Gorwood', 'pet_type':'Golden brush-tailed possum', 'pet_name':'Switchable object-oriented functionalities' },
    { 'id':2, 'first_name':'Bronnie', 'last_name':'Exposito', 'pet_type':'Swan, trumpeter', 'pet_name':'Intuitive optimizing synergy' },
    { 'id':3, 'first_name':'Jackelyn', 'last_name':'Hallyburton', 'pet_type':'Gecko, tokay', 'pet_name':'Fundamental bi-directional encryption' },
    { 'id':4, 'first_name':'Sydney', 'last_name':'Keming', 'pet_type':'Snake, tiger', 'pet_name':'Operative contextually-based Graphic Interface' },
    { 'id':5, 'first_name':'Malia', 'last_name':'Somers', 'pet_type':'Euro wallaby', 'pet_name':'Switchable user-facing time-frame' },
    { 'id':6, 'first_name':'Remy', 'last_name':'Tollmache', 'pet_type':'Common melba finch', 'pet_name':'Virtual 5th generation service-desk' },
    { 'id':7, 'first_name':'Cathleen', 'last_name':'McElvine', 'pet_type':'Sloth, two-toed', 'pet_name':'Realigned background protocol' },
    { 'id':8, 'first_name':'Melania', 'last_name':'Tarry', 'pet_type':'Field flicker', 'pet_name':'Multi-channelled encompassing database' },
    { 'id':9, 'first_name':'Elga', 'last_name':'Igonet', 'pet_type':'Common waterbuck', 'pet_name':'Up-sized full-range database' },
    { 'id':10, 'first_name':'Tomkin', 'last_name':'Brucker', 'pet_type':'Colobus, black and white', 'pet_name':'Quality-focused leading edge budgetary management' },
    { 'id':11, 'first_name':'Edythe', 'last_name':'Eich', 'pet_type':'African skink', 'pet_name':'Open-architected user-facing installation' },
    { 'id':12, 'first_name':'Kalila', 'last_name':'Agget', 'pet_type':'Common green iguana', 'pet_name':'Reduced background utilisation' },
    { 'id':13, 'first_name':'Adah', 'last_name':'Teas', 'pet_type':'Savannah deer', 'pet_name':'Innovative intangible instruction set' },
    { 'id':14, 'first_name':'Bard', 'last_name':'Lambrechts', 'pet_type':'Long-tailed spotted cat', 'pet_name':'Decentralized even-keeled contingency' },
    { 'id':15, 'first_name':'Norry', 'last_name':'Attawell', 'pet_type':'Eurasian hoopoe', 'pet_name':'Seamless logistical standardization' },
    { 'id':16, 'first_name':'Leshia', 'last_name':'Reuble', 'pet_type':'Roadrunner, greater', 'pet_name':'Cloned impactful methodology' },
    { 'id':17, 'first_name':'Dorita', 'last_name':'Keable', 'pet_type':'Owl, snowy', 'pet_name':'Self-enabling coherent superstructure' },
    { 'id':18, 'first_name':'Grant', 'last_name':'Melmeth', 'pet_type':'Macaw, blue and yellow', 'pet_name':'Proactive human-resource solution' },
    { 'id':19, 'first_name':'Willa', 'last_name':'Philo', 'pet_type':'Dove, ring', 'pet_name':'Synergized actuating adapter' },
    { 'id':20, 'first_name':'Nelli', 'last_name':'Connal', 'pet_type':'Cape wild cat', 'pet_name':'Re-contextualized well-modulated capacity' },
    { 'id':21, 'first_name':'Elfie', 'last_name':'Purkess', 'pet_type':'Chuckwalla', 'pet_name':'Assimilated maximized info-mediaries' },
    { 'id':22, 'first_name':'Anica', 'last_name':'Caseley', 'pet_type':'Cape cobra', 'pet_name':'Triple-buffered national collaboration' },
    { 'id':23, 'first_name':'Thorin', 'last_name':'Bydaway', 'pet_type':'Brush-tailed phascogale', 'pet_name':'Organic asynchronous info-mediaries' },
    { 'id':24, 'first_name':'Yolande', 'last_name':'Mocher', 'pet_type':'Short-beaked echidna', 'pet_name':'Programmable demand-driven internet solution' },
    { 'id':25, 'first_name':'Astra', 'last_name':'Ells', 'pet_type':'Wapiti, elk,', 'pet_name':'Business-focused 24/7 info-mediaries' },
    { 'id':26, 'first_name':'Jerrilyn', 'last_name':'Renahan', 'pet_type':'Langur, gray', 'pet_name':'Profit-focused user-facing middleware' },
    { 'id':27, 'first_name':'Nickolas', 'last_name':'Bourthoumieux', 'pet_type':"Cook's tree boa", 'pet_name':'Vision-oriented modular analyzer' },
    { 'id':28, 'first_name':'Temple', 'last_name':'Currin', 'pet_type':'Suricate', 'pet_name':'Front-line encompassing initiative' },
    { 'id':29, 'first_name':'Patton', 'last_name':'Doughton', 'pet_type':'Peacock, blue', 'pet_name':'Re-contextualized fault-tolerant migration' },
    { 'id':30, 'first_name':'Ashla', 'last_name':'Godly', 'pet_type':'Southern hairy-nosed wombat', 'pet_name':'Team-oriented leading edge database' },
    { 'id':31, 'first_name':'Gerta', 'last_name':'Penlington', 'pet_type':'Ant (unidentified)', 'pet_name':'Sharable well-modulated array' },
    { 'id':32, 'first_name':'Goraud', 'last_name':'Barnaby', 'pet_type':'Crow, pied', 'pet_name':'Innovative zero tolerance algorithm' },
    { 'id':33, 'first_name':'Douglass', 'last_name':'Elgie', 'pet_type':'Galapagos tortoise', 'pet_name':'Organic upward-trending open architecture' },
    { 'id':34, 'first_name':'Consuelo', 'last_name':'Nelsen', 'pet_type':'Suricate', 'pet_name':'Ergonomic human-resource system engine' },
    { 'id':35, 'first_name':'Katha', 'last_name':'Benini', 'pet_type':'Wallaby, whip-tailed', 'pet_name':'Innovative 4th generation architecture' },
    { 'id':36, 'first_name':'Kippie', 'last_name':'Scyone', 'pet_type':'Greater blue-eared starling', 'pet_name':'User-friendly cohesive approach' },
    { 'id':37, 'first_name':'Romy', 'last_name':'Wadforth', 'pet_type':'Cape raven', 'pet_name':'Switchable systemic strategy' },
    { 'id':38, 'first_name':'Dulcie', 'last_name':'Rickardes', 'pet_type':'Pied avocet', 'pet_name':'Front-line contextually-based instruction set' },
    { 'id':39, 'first_name':'Isidore', 'last_name':'Readie', 'pet_type':'Lapwing (unidentified)', 'pet_name':'Configurable scalable internet solution' },
    { 'id':40, 'first_name':'Lorita', 'last_name':'Searsby', 'pet_type':'Galapagos penguin', 'pet_name':'Diverse tertiary hub' },
    { 'id':41, 'first_name':'Saxe', 'last_name':'Scurfield', 'pet_type':'Sloth bear', 'pet_name':'Grass-roots radical success' },
    { 'id':42, 'first_name':'Caspar', 'last_name':'Chagg', 'pet_type':'Chameleon (unidentified)', 'pet_name':'Phased context-sensitive synergy' },
    { 'id':43, 'first_name':'Lainey', 'last_name':'Dallander', 'pet_type':'Pale-throated three-toed sloth', 'pet_name':'Upgradable static implementation' },
    { 'id':44, 'first_name':'Elene', 'last_name':'Butterley', 'pet_type':"Lion, steller's sea", 'pet_name':'Implemented 24/7 projection' },
    { 'id':45, 'first_name':'Alicia', 'last_name':'Purseglove', 'pet_type':'Euro wallaby', 'pet_name':'Future-proofed fresh-thinking matrices' },
    { 'id':46, 'first_name':'Lauryn', 'last_name':'Prettyjohn', 'pet_type':'Langur, gray', 'pet_name':'Cross-group 5th generation throughput' },
    { 'id':47, 'first_name':'Rudie', 'last_name':'Eade', 'pet_type':"Boa, cook's tree", 'pet_name':'Pre-emptive impactful parallelism' },
    { 'id':48, 'first_name':'Norma', 'last_name':'Allum', 'pet_type':'Common raccoon', 'pet_name':'Adaptive mobile application' },
    { 'id':49, 'first_name':'Yves', 'last_name':'Kienzle', 'pet_type':'Goose, andean', 'pet_name':'Enhanced multi-state focus group' },
    { 'id':50, 'first_name':'Colas', 'last_name':'Klimentyev', 'pet_type':'Sheep, american bighorn', 'pet_name':'Fundamental eco-centric monitoring' }]
];