export const Customers = [
  [{ 'id':1, 'first_name':'Kippie', 'location':'Pore', 'favorite_color':'Turquoise', 'favorite_movie':'Village of the Damned' },
    { 'id':2, 'first_name':'Arlina', 'location':'Duodaoshi', 'favorite_color':'Pink', 'favorite_movie':'Benigni' },
    { 'id':3, 'first_name':'Town', 'location':'Chư Sê', 'favorite_color':'Fuscia', 'favorite_movie':'Panda! Go Panda! (Panda kopanda)' },
    { 'id':4, 'first_name':'Kasey', 'location':'Berlín', 'favorite_color':'Green', 'favorite_movie':'Shattered Glass' },
    { 'id':5, 'first_name':'Lotty', 'location':'Burträsk', 'favorite_color':'Teal', 'favorite_movie':'Man Without a Past, The (Mies vailla menneisyyttä)' },
    { 'id':6, 'first_name':'Roger', 'location':'Sacramento', 'favorite_color':'Purple', 'favorite_movie':'Rosvo Roope' },
    { 'id':7, 'first_name':'Neysa', 'location':'Větřní', 'favorite_color':'Violet', 'favorite_movie':'Millhaven' },
    { 'id':8, 'first_name':'Ariela', 'location':'Bertoua', 'favorite_color':'Teal', 'favorite_movie':'Lost Horizon' },
    { 'id':9, 'first_name':'Priscella', 'location':'Invermere', 'favorite_color':'Crimson', 'favorite_movie':'One-Eyed Monster' },
    { 'id':10, 'first_name':'Ilene', 'location':'Smoky Lake', 'favorite_color':'Orange', 'favorite_movie':'Longshots, The' },
    { 'id':11, 'first_name':'Kenn', 'location':'Tarbes', 'favorite_color':'Puce', 'favorite_movie':'Forced Vengeance' },
    { 'id':12, 'first_name':'Karrie', 'location':'Paraćin', 'favorite_color':'Indigo', 'favorite_movie':"Mad Ron's Prevues from Hell" },
    { 'id':13, 'first_name':'Wylie', 'location':'Agarsin', 'favorite_color':'Khaki', 'favorite_movie':'Podwórka' },
    { 'id':14, 'first_name':'Niven', 'location':'Jiangjing', 'favorite_color':'Red', 'favorite_movie':'Mountain Men, The' },
    { 'id':15, 'first_name':'Carmita', 'location':'Taoling', 'favorite_color':'Yellow', 'favorite_movie':'Sea Wolves, The' },
    { 'id':16, 'first_name':'Delmar', 'location':'Kuching', 'favorite_color':'Orange', 'favorite_movie':'Thawing Out (La fonte des neiges) ' },
    { 'id':17, 'first_name':'Maia', 'location':'Bua Yai', 'favorite_color':'Purple', 'favorite_movie':'Year One' },
    { 'id':18, 'first_name':'Silas', 'location':'Mauren', 'favorite_color':'Yellow', 'favorite_movie':'On His Own (a.k.a. My Apprenticeship) (V lyudyakh)' },
    { 'id':19, 'first_name':'Brita', 'location':'Dondar Quşçu', 'favorite_color':'Mauv', 'favorite_movie':'Purple Butterfly (Zi hudie)' },
    { 'id':20, 'first_name':'Raquel', 'location':'Tha Mai', 'favorite_color':'Violet', 'favorite_movie':'Airplane II: The Sequel' },
    { 'id':21, 'first_name':'Catie', 'location':'Dijon', 'favorite_color':'Khaki', 'favorite_movie':'Adonis Factor, The' },
    { 'id':22, 'first_name':'Drew', 'location':'Svetlyy Yar', 'favorite_color':'Indigo', 'favorite_movie':'Butterfly, The (Papillon, Le)' },
    { 'id':23, 'first_name':'Audy', 'location':'Jiangyou', 'favorite_color':'Purple', 'favorite_movie':'Crimson Petal and the White, The' },
    { 'id':24, 'first_name':'Sella', 'location':'Matias Olímpio', 'favorite_color':'Yellow', 'favorite_movie':'Micmacs (Micmacs à tire-larigot)' },
    { 'id':25, 'first_name':'Foster', 'location':'Yiqian', 'favorite_color':'Teal', 'favorite_movie':'Anthony Adverse' },
    { 'id':26, 'first_name':'Elfrida', 'location':'Strizhi', 'favorite_color':'Blue', 'favorite_movie':'Rabbit Without Ears (Keinohrhasen)' },
    { 'id':27, 'first_name':'Toby', 'location':'Mutang', 'favorite_color':'Blue', 'favorite_movie':'Importance of Tying Your Own Shoes, The (Hur många lingon finns det i världen?)' },
    { 'id':28, 'first_name':'Wylie', 'location':'Ábrego', 'favorite_color':'Turquoise', 'favorite_movie':"Man's Job (Miehen työ)" },
    { 'id':29, 'first_name':'Tedda', 'location':'Annapolis', 'favorite_color':'Violet', 'favorite_movie':'Against the Ropes' },
    { 'id':30, 'first_name':'Godfree', 'location':'Rosario', 'favorite_color':'Teal', 'favorite_movie':"Teacher's Pet" },
    { 'id':31, 'first_name':'Jobie', 'location':'Harstad', 'favorite_color':'Violet', 'favorite_movie':'House II: The Second Story' },
    { 'id':32, 'first_name':'Carmencita', 'location':'Baoyang', 'favorite_color':'Pink', 'favorite_movie':'Steel Helmet, The' },
    { 'id':33, 'first_name':'Ana', 'location':'Senglea', 'favorite_color':'Orange', 'favorite_movie':'Samurai (Samourais)' },
    { 'id':34, 'first_name':'Dalli', 'location':'Melaka', 'favorite_color':'Indigo', 'favorite_movie':'Armageddon (Armaguedon)' },
    { 'id':35, 'first_name':'Kirbee', 'location':'Valcheta', 'favorite_color':'Violet', 'favorite_movie':'Raid' },
    { 'id':36, 'first_name':'Hayden', 'location':'Haradzyeya', 'favorite_color':'Puce', 'favorite_movie':'Asterix in Britain (Astérix chez les Bretons)' },
    { 'id':37, 'first_name':'Pryce', 'location':'Nan’an', 'favorite_color':'Maroon', 'favorite_movie':'Happy Birthday to a Beautiful Woman' },
    { 'id':38, 'first_name':'Fons', 'location':'Bela-Bela', 'favorite_color':'Crimson', 'favorite_movie':'Hamlet' },
    { 'id':39, 'first_name':'Dannel', 'location':'Kekeri', 'favorite_color':'Pink', 'favorite_movie':"Amy's O (a.k.a. Amy's Orgasm)" },
    { 'id':40, 'first_name':'Mose', 'location':'Lajedo', 'favorite_color':'Purple', 'favorite_movie':'Saints and Soldiers' },
    { 'id':41, 'first_name':'Tana', 'location':'Älvsjö', 'favorite_color':'Purple', 'favorite_movie':'Drive-In Horrorshow' },
    { 'id':42, 'first_name':'Harrietta', 'location':'Boychinovtsi', 'favorite_color':'Violet', 'favorite_movie':'Monsterman (Monsterimies)' },
    { 'id':43, 'first_name':'Leigha', 'location':'Kalasin', 'favorite_color':'Goldenrod', 'favorite_movie':'Saratoga Trunk' },
    { 'id':44, 'first_name':'Torre', 'location':'Guapimirim', 'favorite_color':'Red', 'favorite_movie':'Jim Norton: Please Be Offended' },
    { 'id':45, 'first_name':'Daffi', 'location':'Trelleborg', 'favorite_color':'Teal', 'favorite_movie':'Poker House, The' },
    { 'id':46, 'first_name':'Cathryn', 'location':'Dejilin', 'favorite_color':'Blue', 'favorite_movie':'Girl from Jones Beach, The' },
    { 'id':47, 'first_name':'Conn', 'location':'Néo Psychikó', 'favorite_color':'Yellow', 'favorite_movie':'In the Name of the Law' },
    { 'id':48, 'first_name':'Brunhilda', 'location':'Paris 04', 'favorite_color':'Blue', 'favorite_movie':'Kwik Stop' },
    { 'id':49, 'first_name':'Kial', 'location':'Youguzhuang', 'favorite_color':'Teal', 'favorite_movie':'Soft Fruit' },
    { 'id':50, 'first_name':'Aline', 'location':'Sumberkrajan', 'favorite_color':'Violet', 'favorite_movie':'Love Before Breakfast' },
    { 'id':51, 'first_name':'Rollo', 'location':'Straszyn', 'favorite_color':'Crimson', 'favorite_movie':'Kummeli V' },
    { 'id':52, 'first_name':'Karlan', 'location':'José Bonifácio', 'favorite_color':'Red', 'favorite_movie':"Muriel, or The Time of Return (Muriel ou Le temps d'un retour)" },
    { 'id':53, 'first_name':'Rafi', 'location':'Nanganumba', 'favorite_color':'Mauv', 'favorite_movie':'Gaucho, The' },
    { 'id':54, 'first_name':'Roxana', 'location':'Xiaoguai', 'favorite_color':'Goldenrod', 'favorite_movie':'Volcano (Eldfjall)' },
    { 'id':55, 'first_name':'Gabriella', 'location':'Yingpu', 'favorite_color':'Crimson', 'favorite_movie':"August Mordum's Underground" },
    { 'id':56, 'first_name':'Shirlene', 'location':'Palmar de Varela', 'favorite_color':'Aquamarine', 'favorite_movie':'Winners and Sinners (Qi mou miao ji: Wu fu xing)' },
    { 'id':57, 'first_name':'Talia', 'location':'Stakhanov', 'favorite_color':'Mauv', 'favorite_movie':'Mystery of the 13th Guest' },
    { 'id':58, 'first_name':'Martie', 'location':'Piła', 'favorite_color':'Khaki', 'favorite_movie':'Grotesque' },
    { 'id':59, 'first_name':'Riannon', 'location':'Citangtu Kaler', 'favorite_color':'Pink', 'favorite_movie':'Earth (Tierra)' },
    { 'id':60, 'first_name':'Beverly', 'location':'Palmas', 'favorite_color':'Blue', 'favorite_movie':"Diary of a Country Priest (Journal d'un curé de campagne)" },
    { 'id':61, 'first_name':'Kendra', 'location':'Iqaluit', 'favorite_color':'Orange', 'favorite_movie':'Shot in the Heart' },
    { 'id':62, 'first_name':'Clarette', 'location':'Alegre', 'favorite_color':'Yellow', 'favorite_movie':'Marrying Kind, The' },
    { 'id':63, 'first_name':'Hussein', 'location':'Fray Luis A. Beltrán', 'favorite_color':'Maroon', 'favorite_movie':'Earth vs. The Spider' },
    { 'id':64, 'first_name':'Douglas', 'location':'Cibodas', 'favorite_color':'Red', 'favorite_movie':'Next Friday' },
    { 'id':65, 'first_name':'Emmet', 'location':'Cilangkap', 'favorite_color':'Aquamarine', 'favorite_movie':"Midsummer Night's Sex Comedy, A" },
    { 'id':66, 'first_name':'Laurence', 'location':'Dan Makham Tia', 'favorite_color':'Red', 'favorite_movie':'Ichi' },
    { 'id':67, 'first_name':'Flossy', 'location':'Shënmëri', 'favorite_color':'Indigo', 'favorite_movie':'Grandmother' },
    { 'id':68, 'first_name':'Maynord', 'location':'Guayaybi', 'favorite_color':'Goldenrod', 'favorite_movie':'Monster Squad, The' },
    { 'id':69, 'first_name':'Hilliary', 'location':'Chaeryŏng-ŭp', 'favorite_color':'Green', 'favorite_movie':"Brown's Requiem" },
    { 'id':70, 'first_name':'Mina', 'location':'Gunjur Kuta', 'favorite_color':'Maroon', 'favorite_movie':'Tomorrow, When the War Began' },
    { 'id':71, 'first_name':'Toddy', 'location':'Linjiang', 'favorite_color':'Indigo', 'favorite_movie':'Runaway' },
    { 'id':72, 'first_name':'Donna', 'location':'Pag', 'favorite_color':'Aquamarine', 'favorite_movie':"Losin' It" },
    { 'id':73, 'first_name':'Ignacius', 'location':'Wang Thonglang', 'favorite_color':'Puce', 'favorite_movie':'Catered Affair, The' },
    { 'id':74, 'first_name':'Francene', 'location':'Taiping', 'favorite_color':'Yellow', 'favorite_movie':'It Follows' },
    { 'id':75, 'first_name':'Eliza', 'location':'Lewobelek', 'favorite_color':'Indigo', 'favorite_movie':"Brother's War" },
    { 'id':76, 'first_name':'Karoly', 'location':'Pho Thale', 'favorite_color':'Crimson', 'favorite_movie':'Snake and Crane Arts of Shaolin (She hao ba bu)' },
    { 'id':77, 'first_name':'Rolph', 'location':'Monte Novo', 'favorite_color':'Maroon', 'favorite_movie':'Home Movie' },
    { 'id':78, 'first_name':'Winnah', 'location':'Chuntai', 'favorite_color':'Aquamarine', 'favorite_movie':'All Dogs Christmas Carol, An' },
    { 'id':79, 'first_name':'Vasily', 'location':'Trzebunia', 'favorite_color':'Yellow', 'favorite_movie':'Simon & the Oaks' },
    { 'id':80, 'first_name':'Rafferty', 'location':'Tampakan', 'favorite_color':'Blue', 'favorite_movie':'Harry Potter and the Half-Blood Prince' },
    { 'id':81, 'first_name':'Loree', 'location':'Fuwah', 'favorite_color':'Maroon', 'favorite_movie':'Attack of the Killer Tomatoes!' },
    { 'id':82, 'first_name':'Bren', 'location':'Wufeng', 'favorite_color':'Turquoise', 'favorite_movie':'Sharktopus' },
    { 'id':83, 'first_name':'Sauncho', 'location':'Altona', 'favorite_color':'Red', 'favorite_movie':'Ice Age 4: Continental Drift' },
    { 'id':84, 'first_name':'Carly', 'location':'Chengxi', 'favorite_color':'Violet', 'favorite_movie':'Runaway Bride' },
    { 'id':85, 'first_name':'Munmro', 'location':'Ibiúna', 'favorite_color':'Pink', 'favorite_movie':'Turn Me On, Dammit! (Få meg på, for faen)' },
    { 'id':86, 'first_name':'Saul', 'location':'Maquiapo', 'favorite_color':'Purple', 'favorite_movie':'Diary of Anne Frank, The' },
    { 'id':87, 'first_name':'Stanfield', 'location':'Lishan', 'favorite_color':'Crimson', 'favorite_movie':'Behaving Badly' },
    { 'id':88, 'first_name':'Cullie', 'location':'Jumpangdua', 'favorite_color':'Turquoise', 'favorite_movie':'Love of Siam, The (Rak haeng Siam)' },
    { 'id':89, 'first_name':'Rossie', 'location':'Al ‘Udayn', 'favorite_color':'Orange', 'favorite_movie':'Ed' },
    { 'id':90, 'first_name':'Gypsy', 'location':'Maskinongé', 'favorite_color':'Teal', 'favorite_movie':'Babymakers, The' },
    { 'id':91, 'first_name':'Axe', 'location':'Lyubertsy', 'favorite_color':'Fuscia', 'favorite_movie':'The Man From The Alamo' },
    { 'id':92, 'first_name':'Ruprecht', 'location':'Valleymount', 'favorite_color':'Khaki', 'favorite_movie':'Generation Iron' },
    { 'id':93, 'first_name':'Allyson', 'location':'Guapimirim', 'favorite_color':'Khaki', 'favorite_movie':'The Swedish Moment' },
    { 'id':94, 'first_name':'Lon', 'location':'La Courneuve', 'favorite_color':'Khaki', 'favorite_movie':'In America' },
    { 'id':95, 'first_name':'Pauly', 'location':'Haduohe', 'favorite_color':'Blue', 'favorite_movie':'White Sound, The (Das weiße Rauschen)' },
    { 'id':96, 'first_name':'Augie', 'location':'Dom Pedro', 'favorite_color':'Orange', 'favorite_movie':"Knockin' on Heaven's Door" },
    { 'id':97, 'first_name':'Peterus', 'location':'Sibinal', 'favorite_color':'Puce', 'favorite_movie':'Naked Lunch' },
    { 'id':98, 'first_name':'Leda', 'location':'Ujazd', 'favorite_color':'Pink', 'favorite_movie':'Unconditional Love' },
    { 'id':99, 'first_name':'Ron', 'location':'Oropesa', 'favorite_color':'Fuscia', 'favorite_movie':'Road to Brown, The' },
    { 'id':100, 'first_name':'Berk', 'location':'Luohuang', 'favorite_color':'Purple', 'favorite_movie':'Cabin Fever' }]
];